export const endpoints = {
  login: '/auth/signin',
  register: '/auth/signup',
  patients: '/patient/patients',
  patientsStats: '/patient/stats',
  doctors: '/user/doctors',
  doctorsDropdown: '/user/doctors/dropdown',
  addPatientTreatment: '/patient/addPatientTreatment',
  patient: '/patient/::patientId',
  updatePatient: '/patient/updatePatient',
  patientTreatments: '/treatments/patientTreatments/::patientId',
  treatments: '/treatments',
  deleteTreatment: '/treatments/deleteTreatment/::treatmentId',
  updateTreatment: '/treatments/updateTreatment',
  registerUser: '/user/registerUser',
  verifyRegisteredUser: '/user/verifyRegisteredUser',
  getSchedulers: '/schedulers/all',
  addScheduler: '/schedulers/add',
  updateScheduler: '/schedulers/update',
  me: '/user/me',
};
